<?php>
//
// ETS2MP Homepage language file.
// File: spanish.php
// Language name: Spanish
// Translated name: Español
//

$_lang["download"] = "Descargar";
$_lang["home"] = "Inicio";
$_lang["status"] = "Estado";
$_lang["username"] = "Usuario";
$_lang["password"] = "Contraseña";
$_lang["login"] = "Iniciar Sesión";
$_lang["register"] = "Registrarse";
$_lang["download.latest.version"] = "Descargar última versión";
$_lang["current.release"] = "Versión actual:";
$_lang["language"] = "Idioma";
$_lang["join"] = "UNIRSE";
$_lang["mainpage.join"] = "¡Únete junto a miles entusiastas de camiones online!";
$_lang["ts3.advertisement"] = "Interactúa con otros conductores - haz click para entrar al servidor de TS3.";
$_lang["facebook.advertisement"] = "Últimas noticias en nuestro Facebook.";
$_lang["registration.blocked"] = "El Registro está desactivado - Estamos trabajando en nuevas características que nos obligan a desactivar el registro. Lo reactivaremos cuando terminemos todo y podamos publicar una nueva versión.";
$_lang["invalid.username.password"] = "E-Mail y/o contraseña incorrecta.".;
$_lang["already.logged"] = "Ya estás conectado.";
$_lang["welcome"] = "Bienvenido";
$_lang["logout"] = "Cerrar sesión";
$_lang["bans"] = "Bans";
$_lang["version"] = "Versión";
$_lang["update.time"] = "Actualizado";
$_lang["req.game.version"] = "Versión del juego requerida";
$_lang["requires"] = "Requiere";
$_lang["or.newer"] = "o posterior";
$_lang["game.client"] = "Cliente de Juego";
$_lang["download.no.permissions"] = "Debes iniciar sesión para descargar el mod.";
$_lang["why.create.account"] = "¿Por qué crear una cuenta?<br /> Una cuenta será usada para identificarte en todos los servicios. (Foro, juego, la economía y más). Tenemos previsto utilizarla para introducir una economía y estadisticas personales del conductor en el futuro. Serás capaz de modificar tu propio perfil.";
$_lang["website.title"] = "ETS2MP - Virtual trucking world - Mod multijugador para Euro Truck Simulator 2 un juego de SCS Software";
$_lang["cookies.warning"] = "Este sitio usa <a href="http:/es.wikipedia.org/wiki/Cookie_(informática)">cookies</a>. Si continúa usando este sitio, usted acepta el uso de cookies.";
$_lang["forum"] = "Foro";
$_lang["cannot.create.account.when.logged"] = "No puedes crear una nueva cuenta mientras estás conectado.";
$_lang["successfully.registered"] = "Has sido registrado correctamente. Por favor, comprueba tu E-Mail para activar tu cuenta.";
$_lang["error.unknown"] = "Error desconocido";
$_lang["credentials.taken"] = "El Usuario, E-Mail o SteamId ya está en uso.";
$_lang["error.no.steam.data"] = "Para crear una cuenta de ETS2MP tienes que tener ETS2 en tu cuenta de Steam. Si tienes en tu biblioteca de Steam intenta comprobar que tu perfil sea público. Si es privado, hazlo público y pulsa";
$_lang["register.steam.info"] = "Para registrarte debes iniciar sesión con tu cuenta de Steam. Pulsa el botón de abajo redirigirte a la web de autentificacíón de Steam.";
$_lang["rules.info"] = "Si presionas el botón de registro automáticamente aceptas nuestras normas de la comunidad. Para comprobarlas haz click aquí.";
$_lang["mail"] = "E-Mail";e
$_lang["repeat.mail"] = "Repite E-Mail";
$_lang["new.password"] = "Nueva contraseña";
$_lang["repeat.new.password"] = "Repite nueva contraseña";
$_lang["new.password.summary"] = "Si dejas los campos en blanco la contraseña no será modificada.";
$_lang["old.password"] = "Contraseña anterior";
$_lang["repeat.old.password"] = "Repita contraseña anterior";
$_lang["save.account.data"] = "Guardar información";
$_lang["edit.account"] = "Editar cuenta";
$_lang["forgot.password"] = "¿Contraseña olvidada? Haz click <a href=\"index.php?page=resetPassword\">aquí</a>.";
$_lang["forgot.password.summary"] = "¿Has olvidado tu contraseña? Escribe tu email abajo y pulsa el botón \"Recordar contraseña\".";
$_lang["reminder.button"] = "Recordar contraseña";
$_lang["reset.password"] = "Restablecer contraseña";
$_lang["password.reminder.mail.title"] = "Restablecimiento de contraseña";
$_lang["password.reminder.content"] = "Hola.\n\nAlguien conectado desde IP {0} ha solicitado restablecer la contraseña de tu cuenta de ETS2MP.\n\nPara restablecer tu contraseña haz click en este enlace: {1}.\nSi no has sido tú ignora este correo.\n\nSaludos\nETS2MP Team";
$_lang["new.password.mail.title"] = "Tu nueva contraseña.";
$_lang["new.password.mail.content"] = "Hola.\n\nEsta es tu nueva contraseña: {0}\n\nRecuerda cambiarla inmediatamente tras iniciar sesión.\n\nSaludos\nETS2MP Team";
$_lang["account.activated"] = "Tu cuenta ha sido correctamente activada.";
$_lang["unable.to.activate"] = "Incapaz de activar contraseña, clave inválida o la cuenta ya está activada.";
$_lang["not.activated"] = "Tu cuenta no se ha activado aún. Si no te ha llegado el mensaje de activación haz click <a href=\"index.php?action=resendActivation\">aquí</a> para enviar de nuevo una nueva clave de activación.";
$_lang["force.password.change"] = "Por favor, cambia tu contraseña inmediatamente. Haz click <a href=\"index.php?page=editAccount\">aquí</a> para hacerlo ahora.";
$_lang["forgot.password.link.sent"] = "Revisa tu E-Mail. Te hemos enviado un enlace para restablecer tu contraseña.";
$_lang["forgot.password.sent"] = "Revisa tu E-Mail. Te hemos enviado una nueva contraseña.";
$_lang["forgot.password.invalid.key"] = "Clave de restablecimiento de contraseña inválida.";
$_lang["activation.key.resent"] = "Una nueva clave de activación ha sido enviada a tu correo.";
$_lang["activation.mail.title"] = "Activación de cuenta de ETS2MP.";
$_lang["activation.mail.content"] = "Hola.\n\nEsta es tu clave de activación: {0}\n\nSaludos\nETS2MP Team";
$_lang["no.login"] = "Debes iniciar sesión para poder acceder a esta página..";
$_lang["settings.saved.with.mail"] = "La cuenta ha sido guardada. Revisa tu correo y activa tu cuenta de nuevo.";
$_lang["new.email.in.use"] = "Este E-Mail ya está en uso.";
$_lang["email.does.not.match"] = "Los E-Mails introducidos no coinciden.";
$_lang["invalid.email.format"] = "El E-Mail introducido no es válido.";
$_lang["new.password.does.not.match"] = "Las contraseñas introducidas no coinciden.";
$_lang["too.short.password"] = "La nueva contraseña es demasiado corta. Mínimo: 5 carácteres";
$_lang["old.password.does.not.match"] = "Las contraseñas anteriores no coinciden.";
$_lang["settings.saved"] = "La cuenta ha sido guardada.";
$_lang["invalid.old.password"] = "La contraseña anterior es inválida, incapaz de guardar los cambios.";
$_lang["no.password.change.forced"] = "Para restablecer tu contraseña debes estar desconectado..";
$_lang["password.reminder.edit.account"] = "¿No recuerdas la contraseña? Haz click <a href=\"index.php?page=resetPassword\">aquí</a>.";
$_lang["contact"] = "Contacto";
$_lang["your.mail"] = "E-Mail";
$_lang["content"] = "Mensaje";
$_lang["send"] = "Enviado";
$_lang["contact.message.sent"] = "Gracias por contactar con nosotros. Por favor, espere nuestra respuesta.";
$_lang["topic"] = "Asunto";
$_lang["contact.message.too.short"] = "El mensaje es demasiado corto. Mínimo 10 carácteres.";
$_lang["contact.topic.too.short"] = "El asunto es demasiado corto. Mínimo 10 carácteres.";
$_lang["invalid.mail.forgot.password"] = "No encontramos ninguna cuenta con este E-Mail.";
$_lang["steamid.in.use"] = "Hemos encontrado cuentas de ETS2MP conectadas a esta cuenta de Steam. Si tienes problemas con el registro, por favor <a href=\"http://ets2mp.com/support/\">crea un ticket de Soporte</a>.";
$_lang["mail.does.not.match"] = "Las direcciones de E-Mail introducidas no coinciden..";
$_lang["support"] = "Soporte";
$_lang["profile"] = "Perfil";
$_lang["group"] = "Grupo";
$_lang["banned"] = "Baneado";
$_lang["state"] = "Estado";
$_lang["account.is.activated"] = "La cuenta está activada";
$_lang["account.isnt.actiated"] = "La cuenta no está activada";
$_lang["penalty.history"] = "Historial de sanciones";
$_lang["no.punishments"] = "No hay sanciones que mostrar.";
$_lang["date"] = "Fecha";
$_lang["reason"] = "Razón";
$_lang["type"] = "Tipo";
$_lang["penalty.limit"] = "Sólo el dueño de la cuenta puede ver el historial de sanciones al completo.";
